### ISSUE TITLE
doctests fail in a lot of places

### ISSUE THREAD

**Issue by johanvdw** [watem-sedem/pywatemsedem#9]
I've ignored results for now in github actions, but by running tox -e doctests examples in documentation are tested. Not sure if it relevant, but worth checking.

**Comment by daarende** [comment]
I fixed some syntax errors in the docstrings that were highlighted by the doctests, see https://github.com/watem-sedem/pywatemsedem/pull/60

However,  to make some examples of code actualy work, we need a lot of test data. I don't know if this is worth the effort. 

For example, see https://github.com/watem-sedem/pywatemsedem/pull/60/commits/8bb381139907f66e09cf30f53d04b52b6824b857: I added import statements and made the code look to actualy work, but it does not work as the postprocess objects cannot be made as there is a lack of data. This function generates several doctest failures:

```
Document: api/pywatemsedem
--------------------------
**********************************************************************
File "..\.tox\doctests\Lib\site-packages\pywatemsedem\compare_scenario.py", line ?, in default
Failed example:
    pp1 = PostProcess("molenbeek", 1, 2019, 20, 31370)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\DaanRenders\miniconda3\envs\pywatemsedem\Lib\doctest.py", line 1398, in __run
        exec(compile(example.source, filename, "single",
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     compileflags, True), test.globs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest default[1]>", line 1, in <module>
        pp1 = PostProcess("molenbeek", 1, 2019, 20, 31370)
      File "C:\git\pywatemsedem\.tox\doctests\Lib\site-packages\pywatemsedem\postprocess.py", line 161, in __init__
        self.cfolder.check_home_folder()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "C:\git\pywatemsedem\.tox\doctests\Lib\site-packages\pywatemsedem\io\folders.py", line 24, in check_home_folder
        check_and_create_home_folder(self.home_folder, **options)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\git\pywatemsedem\.tox\doctests\Lib\site-packages\pywatemsedem\io\folders.py", line 106, in check_and_create_home_folder
        check_and_create_folder(
        ~~~~~~~~~~~~~~~~~~~~~~~^
            home_folder, msg_subject=f"Home folder '{home_folder}'", **options
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "C:\git\pywatemsedem\.tox\doctests\Lib\site-packages\pywatemsedem\io\folders.py", line 291, in check_and_create_folder
        raise IOError(msg_subject + " does not exist.")
    OSError: Home folder 'molenbeek' does not exist.
**********************************************************************
File "..\.tox\doctests\Lib\site-packages\pywatemsedem\compare_scenario.py", line ?, in default
Failed example:
    pp2 = PostProcess("molenbeek", 2, 2019, 20, 31370)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\DaanRenders\miniconda3\envs\pywatemsedem\Lib\doctest.py", line 1398, in __run
        exec(compile(example.source, filename, "single",
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     compileflags, True), test.globs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest default[2]>", line 1, in <module>
        pp2 = PostProcess("molenbeek", 2, 2019, 20, 31370)
      File "C:\git\pywatemsedem\.tox\doctests\Lib\site-packages\pywatemsedem\postprocess.py", line 161, in __init__
        self.cfolder.check_home_folder()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "C:\git\pywatemsedem\.tox\doctests\Lib\site-packages\pywatemsedem\io\folders.py", line 24, in check_home_folder
        check_and_create_home_folder(self.home_folder, **options)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\git\pywatemsedem\.tox\doctests\Lib\site-packages\pywatemsedem\io\folders.py", line 106, in check_and_create_home_folder
        check_and_create_folder(
        ~~~~~~~~~~~~~~~~~~~~~~~^
            home_folder, msg_subject=f"Home folder '{home_folder}'", **options
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "C:\git\pywatemsedem\.tox\doctests\Lib\site-packages\pywatemsedem\io\folders.py", line 291, in check_and_create_folder
        raise IOError(msg_subject + " does not exist.")
    OSError: Home folder 'molenbeek' does not exist.
**********************************************************************
File "..\.tox\doctests\Lib\site-packages\pywatemsedem\compare_scenario.py", line ?, in default
Failed example:
    delta_scenario = DeltaScenario(pp1,pp2)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\DaanRenders\miniconda3\envs\pywatemsedem\Lib\doctest.py", line 1398, in __run
        exec(compile(example.source, filename, "single",
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     compileflags, True), test.globs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest default[4]>", line 1, in <module>
        delta_scenario = DeltaScenario(pp1,pp2)
                                       ^^^
    NameError: name 'pp1' is not defined
**********************************************************************
File "..\.tox\doctests\Lib\site-packages\pywatemsedem\compare_scenario.py", line ?, in default
Failed example:
    delta_scenario.comparison_total_sediment_file()
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\DaanRenders\miniconda3\envs\pywatemsedem\Lib\doctest.py", line 1398, in __run
        exec(compile(example.source, filename, "single",
        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     compileflags, True), test.globs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest default[5]>", line 1, in <module>
        delta_scenario.comparison_total_sediment_file()
        ^^^^^^^^^^^^^^
    NameError: name 'delta_scenario' is not defined. Did you mean: 'DeltaScenario'?`
